server:
  port: 8082
spring:
  application:
    name: course-service
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/unicore_courses}
jwt:
  secret: ${JWT_SECRET:unicore-development-secret-key-change-me-please-keep-long}
services:
  notification-url: ${NOTIFICATION_SERVICE_URL:http://localhost:8084}
